# Site identity
baseurl  = "https://godvvvzzz.github.io/"
locale   = "zh-cn"
title    = "VvVzzz Blog"
timeZone = "Asia/Shanghai"

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "zh"

# Make summaries and word counts CJK-aware.
hasCJKLanguage = true

[pagination]
    pagerSize = 5
